version: "3.8"

services:
  app:
    build: ./app
    networks:
      - appnet
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app
    networks:
      - appnet
    restart: unless-stopped

  jenkins:
    build: ./jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
